import type { CaseBlueprint } from "./types";

export const CASES: CaseBlueprint[] = [
  {
    id: "ramesh-stemi",
    version: "ramesh_kale.stemi.inferior.v1",
    title: "Inferior STEMI — district ED",
    specialty: "Emergency / Cardiology",
    durationMin: 15,
    source: "github.com/jaiv007x-cell/naadi",
    contentHash: "80e29c6e203589f222c21115f4e85d22187de5524ea72c88b2235cd3f847df57",
    persona: {
      name: "Ramesh Kale",
      age: 47,
      sex: "M",
      city: "Nagpur",
      language: "mr / hi",
      register: "Low health-literacy Marathi-first; short sentences; gas/acidity folk attribution",
      literacy: "5 years schooling",
      occupation: "Auto-rickshaw driver",
      summary:
        "Chatit jad, ghaam yetoy. 40 minutes of retrosternal heaviness. Blames lunch gas. Family attendant at bedside.",
      openingLine: "Doctor, chatit jad watatay, ghaam yetoy.",
      voice: "ramesh_kale_mr — short Marathi, code-switches ECG/aspirin/PCI when the clinician uses them.",
    },
    briefing:
      "47-year-old auto-rickshaw driver from Nagpur, district ED. Onset 40 minutes ago. Speaks Marathi first. You are the duty clinician. Critical actions are not listed on the screen. Time pressure: 15 minutes.",
    hidden:
      "Inferior wall STEMI (I21.19), RCA territory, RV-preload dependent. T2DM 8y, HTN 3y, gutka, 20 pack-years. Metformin 500 BD, amlodipine 5 OD. Do not give nitroglycerin. Required: 12-lead ECG within 10 min, aspirin 325 chewed, PCI transfer. Seed: content/ramesh-stemi-draft.",
    initialVitals: { hr: 104, sbp: 148, dbp: 92, spo2: 96, rr: 20, pain: 7, tempC: 36.9 },
    orders: [
      { id: "greet_native", label: "Greet in Marathi", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "history", label: "Focused history", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "vitals", label: "Record vitals", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "oxygen", label: "Oxygen if hypoxic", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "iv_access", label: "IV access", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "ecg", label: "12-lead ECG", group: "Diagnostics", minutes: 2, kind: "diagnostic" },
      { id: "v4r", label: "Right-sided leads (V4R)", group: "Diagnostics", minutes: 2, kind: "diagnostic" },
      { id: "troponin", label: "Troponin (qual)", group: "Diagnostics", minutes: 2, kind: "diagnostic" },
      { id: "aspirin", label: "Aspirin 325 mg chew", group: "Medicines", minutes: 1, kind: "med" },
      { id: "statin", label: "Atorvastatin 80 mg", group: "Medicines", minutes: 1, kind: "med" },
      { id: "fluids", label: "Cautious fluids", group: "Medicines", minutes: 2, kind: "med" },
      { id: "morphine", label: "Morphine 2–4 mg", group: "Medicines", minutes: 1, kind: "med" },
      { id: "nitro", label: "Nitroglycerin SL", group: "Medicines", minutes: 1, kind: "med" },
      { id: "iv_epi", label: "IV epinephrine bolus", group: "Medicines", minutes: 1, kind: "med" },
      { id: "consent", label: "Explain & consent", group: "Disposition", minutes: 2, kind: "disposition" },
      { id: "pci_transfer", label: "PCI transfer", group: "Disposition", minutes: 3, kind: "disposition" },
      { id: "thrombolysis", label: "Thrombolyse here", group: "Disposition", minutes: 4, kind: "disposition" },
    ],
    rubric: [
      { id: "stemi.ecg_ordered", label: "12-lead ECG within 10 min", axis: "diagnosis", points: 10, orderId: "ecg", required: true, failCaseOnMiss: true, windowMin: [0, 10] },
      { id: "stemi.aspirin_chewed", label: "Aspirin 325 mg chewed", axis: "procedure", points: 10, orderId: "aspirin", required: true, failCaseOnMiss: true },
      { id: "stemi.pci_transfer", label: "PCI-capable transfer", axis: "timing", points: 5, orderId: "pci_transfer", required: false },
      { id: "stemi.v4r_before_nitrates", label: "V4R before nitrates", axis: "safety", points: 15, orderId: "v4r", required: true, failCaseOnMiss: true },
      { id: "stemi.rv_fluid_rescue", label: "Fluid bolus if RV hypotension", axis: "procedure", points: 12, orderId: "fluids", required: false },
      { id: "stemi.history", label: "Focused history", axis: "procedure", points: 4, orderId: "history", required: false },
      { id: "stemi.statin", label: "Atorvastatin 80 mg", axis: "procedure", points: 3, orderId: "statin", required: false },
      { id: "comm.greet", label: "Native-language greeting", axis: "communication", points: 5, orderId: "greet_native", required: false },
      { id: "comm.consent", label: "Consent in his language", axis: "communication", points: 5, orderId: "consent", required: false },
      { id: "safe.no_nitrate", label: "Nitrate withheld (RV-possible)", axis: "safety", points: 10, orderId: "nitro", required: true, failCaseOnHit: true },
    ],
    competencies: [
      "cardiac.stemi",
      "ecg.inferior",
      "communication.marathi",
      "emergency.triage",
    ],
    findings: {
      ecg: "12-lead: ST elevation in II, III, aVF. Reciprocal depression in aVL. Inferior STEMI, RCA territory. Right-sided leads not yet recorded.",
      v4r: "V4R: ST elevation. RV infarct possible. Preload-dependent. Nitrates contraindicated.",
      troponin: "Qualitative troponin: detectable and rising. Does not change the ECG diagnosis.",
      vitals: "HR 104, BP 148/92, SpO2 96% RA, RR 20, pain 7/10, diaphoretic. Presentation looks ‘stable’. Nitrate is still contraindicated if RV involved.",
      history: "Retrosternal heaviness since lunch, jaw radiation, nausea, diaphoresis. Blames gas. Gutka daily. Sugar tablets sometimes.",
    },
  },
  {
    id: "sunita-preeclampsia",
    version: "sunita_devi.preeclampsia.v1",
    title: "Pre-eclampsia — ASHA referral",
    specialty: "Obstetrics",
    durationMin: 40,
    persona: {
      name: "Sunita Devi",
      age: 34,
      sex: "F",
      city: "Araria, Bihar",
      language: "hi / bho",
      register: "Hindi with Bhojpuri markers, Roman transliteration",
      literacy: "Primary school; defers to mother-in-law",
      occupation: "Home, third pregnancy (G3P2)",
      summary: "32 weeks. Headache, swelling, visual sparks. ASHA referred from village PHC.",
      openingLine: "Doctor saheb, sir mein bahut dard hai. Aankh ke aage jugnu jaise chamak rahe hain.",
      voice: "Quiet, tired, answers through short phrases. Looks at the floor when in pain.",
    },
    briefing:
      "34-year-old woman, G3P2 at 32 weeks, referred by an ASHA from a village PHC in Araria. Headache and swelling. She speaks Hindi with Bhojpuri inflections. Resource-constrained casualty. You are the duty doctor.",
    hidden:
      "Severe pre-eclampsia. BP 168/112, proteinuria, visual scotomata. Do not discharge. Required: repeat BP, urine protein, magnesium sulphate, urgent higher-centre referral. Forbidden: send home, delay for 'observation only'.",
    initialVitals: { hr: 98, sbp: 168, dbp: 112, spo2: 98, rr: 20, pain: 6, tempC: 36.9 },
    orders: [
      { id: "greet_native", label: "Greet in Hindi", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "history", label: "Obstetric history", group: "Bedside", minutes: 4, kind: "bedside" },
      { id: "vitals", label: "Repeat BP (correct cuff)", group: "Bedside", minutes: 3, kind: "bedside" },
      { id: "left_lateral", label: "Left-lateral position", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "urine_protein", label: "Urine protein dip", group: "Diagnostics", minutes: 4, kind: "diagnostic" },
      { id: "fhs", label: "Fetal heart / kick count", group: "Diagnostics", minutes: 4, kind: "diagnostic" },
      { id: "labs", label: "PET bloods (CBC, LFT, creat)", group: "Diagnostics", minutes: 6, kind: "diagnostic" },
      { id: "magnesium", label: "Magnesium sulphate", group: "Medicines", minutes: 5, kind: "med" },
      { id: "labetalol", label: "Labetalol / anti-HTN", group: "Medicines", minutes: 4, kind: "med" },
      { id: "consent", label: "Explain risk to her", group: "Disposition", minutes: 4, kind: "disposition" },
      { id: "referral_higher", label: "Refer to FRU / CEmONC", group: "Disposition", minutes: 6, kind: "disposition" },
      { id: "discharge_home", label: "Reassure & send home", group: "Disposition", minutes: 3, kind: "disposition" },
    ],
    rubric: [
      { id: "bp", label: "Repeat BP with correct technique", axis: "diagnosis", points: 12, orderId: "vitals", required: true, failCaseOnMiss: true },
      { id: "urine", label: "Urine protein", axis: "diagnosis", points: 12, orderId: "urine_protein", required: true, failCaseOnMiss: true },
      { id: "mgso4", label: "Magnesium sulphate", axis: "safety", points: 18, orderId: "magnesium", required: true, failCaseOnMiss: true },
      { id: "refer", label: "Urgent higher-centre referral", axis: "timing", points: 16, orderId: "referral_higher", required: true, failCaseOnMiss: true },
      { id: "history", label: "Obstetric / symptom history", axis: "procedure", points: 8, orderId: "history", required: false },
      { id: "greet", label: "Respectful vernacular greeting", axis: "communication", points: 6, orderId: "greet_native", required: false },
      { id: "consent", label: "Explain in her language", axis: "communication", points: 8, orderId: "consent", required: false },
      { id: "antihypertensive", label: "Treat severe hypertension", axis: "procedure", points: 10, orderId: "labetalol", required: false },
      { id: "home", label: "Discharged home with severe PET", axis: "safety", points: 0, orderId: "discharge_home", required: false, failCaseOnHit: true },
    ],
    competencies: [
      "Severe PET recognition",
      "Proteinuria testing",
      "MgSO4 protocol",
      "Hypertension in pregnancy",
      "Referral under constraint",
      "Respectful maternity care",
    ],
    findings: {
      vitals: "BP 168/112, repeat 170/114. Hyperreflexia. Pedal oedema.",
      urine_protein: "Dipstick protein 3+. Severe pre-eclampsia until proven otherwise.",
      fhs: "Fetal heart 148, regular. Mother reports reduced kicks since yesterday.",
      labs: "Platelets 118k, AST 64, creatinine 1.1 — evolving PET picture.",
    },
  },
  {
    id: "arjun-asthma",
    version: "arjun_reddy.asthma.exacerbation.v1",
    title: "Paediatric asthma — caregiver history",
    specialty: "Paediatrics",
    durationMin: 30,
    persona: {
      name: "Arjun Reddy",
      age: 8,
      sex: "M",
      city: "Hyderabad",
      language: "te / en",
      register: "Telugu-primary with English mix; mother speaks for him",
      literacy: "Child; mother is the historian",
      occupation: "Class 3 student",
      summary: "Night cough, tight chest, after a dusty school function. Mother is the proxy.",
      openingLine: "Amma: Doctor garu, vaadu night antha kosta unnadu. Breathing kastam ga undi.",
      voice: "Mother anxious, fast Telugu-English. Child speaks in fragments, frightened.",
    },
    briefing:
      "8-year-old boy brought by his mother to a Hyderabad paediatric casualty at 23:40. Tight chest and night cough after a dusty school function. Mother is Telugu-primary. History is caregiver-mediated. You are the paediatric MO.",
    hidden:
      "Moderate-severe asthma exacerbation. SpO2 90%, RR 42, tight wheeze. Required: oxygen/sats, nebulised salbutamol, systemic steroid, caregiver history. Forbidden: adult-dose aspirin, sedation for 'calm the child'. Teach spacer before discharge path.",
    initialVitals: { hr: 132, sbp: 102, dbp: 64, spo2: 90, rr: 42, pain: 4, tempC: 37.1 },
    orders: [
      { id: "greet_native", label: "Greet mother in Telugu mix", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "caregiver_history", label: "Caregiver history", group: "Bedside", minutes: 4, kind: "bedside" },
      { id: "vitals", label: "Sats / RR / work of breathing", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "oxygen", label: "Oxygen to target sats", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "peak_flow", label: "Peak flow if able", group: "Diagnostics", minutes: 3, kind: "diagnostic" },
      { id: "nebulized_salbutamol", label: "Nebulised salbutamol", group: "Medicines", minutes: 8, kind: "med" },
      { id: "steroid", label: "Systemic steroid", group: "Medicines", minutes: 3, kind: "med" },
      { id: "aspirin", label: "Aspirin 325 mg", group: "Medicines", minutes: 1, kind: "med" },
      { id: "sedation", label: "Sedate to calm child", group: "Medicines", minutes: 2, kind: "med" },
      { id: "spacer_teach", label: "Spacer technique with mother", group: "Disposition", minutes: 5, kind: "disposition" },
      { id: "consent", label: "Explain plan to mother", group: "Disposition", minutes: 3, kind: "disposition" },
      { id: "referral_higher", label: "Admit / step-up if needed", group: "Disposition", minutes: 5, kind: "disposition" },
    ],
    rubric: [
      { id: "sats", label: "Document sats and work of breathing", axis: "diagnosis", points: 12, orderId: "vitals", required: true, failCaseOnMiss: true },
      { id: "neb", label: "Nebulised salbutamol", axis: "procedure", points: 16, orderId: "nebulized_salbutamol", required: true, failCaseOnMiss: true },
      { id: "steroid", label: "Systemic corticosteroid", axis: "procedure", points: 14, orderId: "steroid", required: true, failCaseOnMiss: true },
      { id: "history", label: "Caregiver-mediated history", axis: "communication", points: 10, orderId: "caregiver_history", required: false },
      { id: "greet", label: "Greet in her language", axis: "communication", points: 6, orderId: "greet_native", required: false },
      { id: "o2", label: "Oxygen to target", axis: "safety", points: 8, orderId: "oxygen", required: false },
      { id: "spacer", label: "Spacer teaching", axis: "procedure", points: 8, orderId: "spacer_teach", required: false },
      { id: "explain", label: "Explain plan to mother", axis: "communication", points: 6, orderId: "consent", required: false },
      { id: "asa", label: "Adult aspirin in a child", axis: "safety", points: 0, orderId: "aspirin", required: false, failCaseOnHit: true },
      { id: "sedate", label: "Sedation for distress", axis: "safety", points: 0, orderId: "sedation", required: false, failCaseOnHit: true },
    ],
    competencies: [
      "Paediatric respiratory assessment",
      "Asthma exacerbation",
      "Caregiver history",
      "Bronchodilator + steroid",
      "Avoid harmful meds",
      "Device teaching",
    ],
    findings: {
      vitals: "SpO2 90% RA, RR 42, HR 132, subcostal recession, bilateral expiratory wheeze.",
      peak_flow: "Unable to perform a reliable peak flow — too dyspnoeic.",
      nebulized_salbutamol: "After first neb: sats 94%, RR 34, wheeze quieter, child less frightened.",
    },
  },
  {
    id: "opd-anaphylaxis",
    version: "ANAPHYLAXIS_OPD_001@1.0.0",
    title: "Anaphylaxis — OPD, post-injection ceftriaxone",
    specialty: "Emergency / Allergy",
    durationMin: 15,
    source: "github.com/jaiv007x-cell/naadi",
    persona: {
      name: "Meena Pawar",
      age: 29,
      sex: "F",
      city: "Wardha",
      language: "mr / hi",
      register: "Marathi-Hindi mix, frightened, short phrases",
      literacy: "Secondary school",
      occupation: "ASHA helper, came for fever injection",
      summary: "Just received IM ceftriaxone in OPD. Itching, tightness, voice changing. Companion present.",
      openingLine: "Doctor… injection nantar khaj, saans takatay. Aawaaz badaltoy.",
      voice: "Panicked, whispering, Marathi-first. Companion answers when she cannot.",
    },
    briefing:
      "OPD, district hospital Wardha. A 29-year-old woman received IM ceftriaxone for fever five minutes ago. She is itchy, breathless, voice changing. You are the MO in the injection room. Critical actions are not listed on the screen.",
    hidden:
      "Anaphylaxis post-ceftriaxone. Required: name it, IM adrenaline 0.3–0.5 mg within 5 min, withhold IV adrenaline bolus, do not repeat ceftriaxone. Supporting: oxygen ≥6 L, NS bolus, supine legs raised, hydrocortisone, H1, airway ready, observe biphasic. Rubric from services/pratibimb/app/cases/rubrics/anaphylaxis.py.",
    initialVitals: { hr: 128, sbp: 82, dbp: 48, spo2: 90, rr: 28, pain: 4, tempC: 37.4 },
    orders: [
      { id: "greet_native", label: "Name the emergency / call for help", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "history", label: "Allergy history", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "vitals", label: "Repeat vitals", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "position_supine_legs_raised", label: "Supine, legs raised", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "oxygen", label: "High-flow oxygen ≥6 L", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "adrenaline_im", label: "Adrenaline 0.5 mg IM", group: "Medicines", minutes: 1, kind: "med" },
      { id: "adrenaline_iv", label: "Adrenaline IV bolus", group: "Medicines", minutes: 1, kind: "med" },
      { id: "iv_fluids", label: "NS bolus ≥500 mL", group: "Medicines", minutes: 2, kind: "med" },
      { id: "hydrocortisone", label: "Hydrocortisone 100 mg IV", group: "Medicines", minutes: 2, kind: "med" },
      { id: "pheniramine", label: "Pheniramine IV", group: "Medicines", minutes: 1, kind: "med" },
      { id: "metoprolol", label: "Metoprolol IV", group: "Medicines", minutes: 1, kind: "med" },
      { id: "ceftriaxone", label: "Repeat ceftriaxone", group: "Medicines", minutes: 1, kind: "med" },
      { id: "prepare_intubation", label: "Prepare airway trolley", group: "Disposition", minutes: 2, kind: "disposition" },
      { id: "allergy_documented", label: "Document allergy", group: "Disposition", minutes: 1, kind: "disposition" },
      { id: "observe_biphasic", label: "Observe for biphasic reaction", group: "Disposition", minutes: 2, kind: "disposition" },
    ],
    rubric: [
      { id: "dx.anaphylaxis", label: "Anaphylaxis named", axis: "diagnosis", points: 10, orderId: "greet_native", required: true, failCaseOnMiss: true, windowMin: [0, 3] },
      { id: "act.adrenaline_im", label: "IM adrenaline 0.3–0.5 mg within 5 min", axis: "procedure", points: 15, orderId: "adrenaline_im", required: true, failCaseOnMiss: true, windowMin: [0, 5] },
      { id: "act.oxygen", label: "High-flow oxygen", axis: "procedure", points: 6, orderId: "oxygen", required: false },
      { id: "act.iv_fluids", label: "NS bolus ≥500 mL", axis: "procedure", points: 8, orderId: "iv_fluids", required: false },
      { id: "act.position", label: "Supine, legs raised", axis: "procedure", points: 4, orderId: "position_supine_legs_raised", required: false },
      { id: "act.hydrocortisone", label: "IV hydrocortisone", axis: "procedure", points: 6, orderId: "hydrocortisone", required: false },
      { id: "act.antihistamine", label: "IV H1 antihistamine", axis: "procedure", points: 5, orderId: "pheniramine", required: false },
      { id: "act.airway_ready", label: "Airway equipment ready", axis: "safety", points: 5, orderId: "prepare_intubation", required: false },
      { id: "safe.iv_adrenaline_withheld", label: "IV adrenaline bolus withheld", axis: "safety", points: 10, orderId: "adrenaline_iv", required: true, failCaseOnHit: true },
      { id: "safe.allergen_not_repeated", label: "Ceftriaxone not repeated", axis: "safety", points: 6, orderId: "ceftriaxone", required: true, failCaseOnHit: true },
      { id: "safe.beta_blocker_withheld", label: "Beta-blocker withheld", axis: "safety", points: 6, orderId: "metoprolol", required: false, failCaseOnHit: true },
      { id: "safe.allergy_documented", label: "Allergy documented", axis: "safety", points: 4, orderId: "allergy_documented", required: false },
      { id: "safe.observation_period", label: "Biphasic observation", axis: "safety", points: 4, orderId: "observe_biphasic", required: false },
    ],
    competencies: [
      "dx.allergic_emergency",
      "rx.anaphylaxis_first_line",
      "safety.route_selection",
      "safety.allergen_avoidance",
    ],
    findings: {
      greet_native: "You say it out loud: anaphylaxis. The injection-room nurse starts pulling the emergency tray.",
      vitals: "HR 128, BP 82/48, SpO2 90%, urticaria spreading, mild stridor on inspiration.",
      history: "No known drug allergy on the OPD slip. First time ceftriaxone. Companion: 'Fever injection diya, ab yeh.'",
      adrenaline_im: "IM adrenaline given. Within a minute voice is clearer, BP climbing.",
      oxygen: "15 L non-rebreather on. SpO2 climbing.",
    },
  },
  {
    id: "aarav-sepsis",
    version: "baby_aarav.neonatal_sepsis.eos.v1",
    title: "Early-onset neonatal sepsis — private nursing home",
    specialty: "Neonatal / Nursing",
    durationMin: 20,
    source: "github.com/jaiv007x-cell/naadi",
    contentHash: "75930a37056f0569de35930cfd875f9cf482aaea6cd6618e113cc3cfa4ccb4ff",
    persona: {
      name: "Baby Aarav",
      age: 0,
      sex: "M",
      city: "Chennai",
      language: "ta / en (via mother)",
      register: "Proxy: Meera speaks. Tamil-primary, English-functional. Minimizes early.",
      literacy: "Neonate; mother is school teacher",
      occupation: "3-day-old term neonate, 2.9 kg",
      summary: "Poor feeding, tachypnea, warm to touch. Discharged at 24h from nursing home.",
      openingLine: "Doctor, kuzhandhai saapadala, udal soodu maathiri irukku. Maybe he is just sleepy?",
      voice: "Meera (mother) — anxious but articulate. Mother-in-law said wait till morning.",
      informant: { name: "Meera", relation: "mother", age: 26 },
    },
    briefing:
      "3-day-old term male, 2.9 kg, private nursing home ER Chennai. Brought by first-time mother Meera — she is the interaction surface; the baby cannot speak. Day-3 poor feeding, tachypnea, fever. PROM and inadequate intrapartum prophylaxis are buried in history. 20-minute clock.",
    hidden:
      "Early-onset neonatal sepsis. PROM 22h, single inadequate ampicillin dose, no GBS screen. Hypothermia after initial fever = progression trap. Required: danger-sign cluster, warmer, sepsis screen, amp+gent NNF first-line, 10 ml/kg NS (not 20). Forbidden: antipyretic-only management, 20 ml/kg bolus, LP while desaturating.",
    initialVitals: { hr: 172, sbp: 62, dbp: 38, spo2: 94, rr: 68, pain: 0, tempC: 38.6 },
    orders: [
      { id: "greet_meera", label: "Greet Meera in Tamil", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "proxy_history", label: "Proxy birth & feeding history", group: "Bedside", minutes: 3, kind: "bedside" },
      { id: "neonatal_vitals", label: "Full neonatal assessment", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "warmer", label: "Radiant warmer / KMC", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "glucose", label: "Bedside glucose", group: "Diagnostics", minutes: 2, kind: "diagnostic" },
      { id: "sepsis_screen", label: "CBC, CRP, I:T ratio", group: "Diagnostics", minutes: 4, kind: "diagnostic" },
      { id: "blood_culture", label: "Blood culture before abx", group: "Diagnostics", minutes: 3, kind: "diagnostic" },
      { id: "amp_gent", label: "Ampicillin + gentamicin (NNF)", group: "Medicines", minutes: 3, kind: "med" },
      { id: "cefotaxime", label: "Cefotaxime if meningitis concern", group: "Medicines", minutes: 2, kind: "med" },
      { id: "fluid_10", label: "NS bolus 10 ml/kg", group: "Medicines", minutes: 2, kind: "med" },
      { id: "fluid_20", label: "NS bolus 20 ml/kg (PALS reflex)", group: "Medicines", minutes: 2, kind: "med" },
      { id: "antipyretic_only", label: "Paracetamol only, observe", group: "Medicines", minutes: 1, kind: "med" },
      { id: "lp", label: "Lumbar puncture", group: "Diagnostics", minutes: 5, kind: "diagnostic" },
      { id: "explain_parents", label: "Explain gravity without panic", group: "Disposition", minutes: 3, kind: "disposition" },
      { id: "refer_nicu", label: "Refer to NICU / higher centre", group: "Disposition", minutes: 4, kind: "disposition" },
    ],
    rubric: [
      { id: "neo.danger_cluster", label: "Danger-sign cluster in first 10 min", axis: "diagnosis", points: 14, orderId: "neonatal_vitals", required: true, failCaseOnMiss: true, windowMin: [0, 10] },
      { id: "neo.thermal", label: "Warmer / thermal care initiated", axis: "procedure", points: 10, orderId: "warmer", required: true, failCaseOnMiss: true },
      { id: "neo.empiric_abx", label: "Empiric amp + gent per NNF", axis: "procedure", points: 14, orderId: "amp_gent", required: true, failCaseOnMiss: true },
      { id: "neo.proxy_prom", label: "PROM / prophylaxis elicited from mother", axis: "communication", points: 8, orderId: "proxy_history", required: false },
      { id: "neo.sepsis_screen", label: "Sepsis screen ordered & interpreted", axis: "diagnosis", points: 8, orderId: "sepsis_screen", required: false },
      { id: "neo.fluid_10", label: "10 ml/kg bolus (neonatal dose)", axis: "safety", points: 8, orderId: "fluid_10", required: false },
      { id: "neo.parent_comm", label: "Parental communication register", axis: "communication", points: 6, orderId: "explain_parents", required: false },
      { id: "neo.glucose", label: "Glucose checked", axis: "diagnosis", points: 5, orderId: "glucose", required: false },
      { id: "neo.fluid_20_trap", label: "20 ml/kg bolus in neonate", axis: "safety", points: 0, orderId: "fluid_20", required: false, failCaseOnHit: true },
    ],
    competencies: [
      "neonatal.sepsis",
      "nursing.assessment",
      "communication.tamil",
      "emergency.triage",
    ],
    findings: {
      neonatal_vitals: "HR 172, RR 68 with subcostal retractions, CRT 4s, temp 38.6°C axillary, fontanelle full not tense, mottled extremities.",
      glucose: "Bedside glucose 38 mg/dL — hypoglycemia concurrent with sepsis.",
      sepsis_screen: "TLC low-normal, ANC depressed, I:T ratio elevated, CRP markedly raised.",
      blood_culture: "Culture sent before antibiotics — correct sequence.",
      amp_gent: "Weight-based amp + gent started. First-line per NNF.",
      warmer: "Radiant warmer on. Temperature trend must be read with clinical context — falling temp can mislead.",
      lp: "LP deferred if unstable; if forced while desaturating, baby decompensates.",
    },
  },
  {
    id: "sunita-pph",
    version: "sunita_devi.pph.rural_phc.v1",
    title: "Postpartum hemorrhage — rural PHC",
    specialty: "Obstetrics / Nursing",
    durationMin: 25,
    persona: {
      name: "Sunita Devi",
      age: 34,
      sex: "F",
      city: "Araria, Bihar",
      language: "hi / bho",
      register: "Hindi with Bhojpuri markers; husband present, pale and frightened",
      literacy: "Primary school; ANM/GNM curriculum context",
      occupation: "Home, postpartum day 2 after home delivery with dai",
      summary: "Still passing clots, dizzy. Husband brought her on motorcycle — 40 min from village.",
      openingLine: "Doctor saheb, khoon ab bhi aa raha hai. Chakkar aa rahe hain. Bachcha theek hai par main gir jaaungi.",
      voice: "Weak, pale, short sentences. Husband answers when she cannot.",
    },
    briefing:
      "34-year-old, day-2 postpartum at a rural PHC in Bihar. Home delivery with traditional birth attendant; placenta reportedly 'complete' but never examined. Pale, tachycardic, hypotensive, ongoing clots. Doctor may be 40 minutes away. You are the ANM/GNM on duty.",
    hidden:
      "Postpartum hemorrhage — retained products vs atonic uterus likely. Required: shock recognition, uterine massage, uterotonic (oxytocin/misoprostol), IV access, escalate to CHC/district, blood availability reality. Forbidden: send home, delay uterotonics, ignore ongoing bleeding.",
    initialVitals: { hr: 128, sbp: 82, dbp: 54, spo2: 97, rr: 22, pain: 5, tempC: 36.8 },
    orders: [
      { id: "greet_native", label: "Greet in Hindi / Bhojpuri", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "history", label: "Delivery & bleeding history", group: "Bedside", minutes: 3, kind: "bedside" },
      { id: "vitals", label: "Shock assessment / vitals", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "iv_access", label: "Large-bore IV access", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "uterine_massage", label: "Bimanual / uterine massage", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "examine_placenta", label: "Examine passed clots / placenta", group: "Diagnostics", minutes: 3, kind: "diagnostic" },
      { id: "hemoglobin", label: "Hb / cross-match request", group: "Diagnostics", minutes: 4, kind: "diagnostic" },
      { id: "oxytocin", label: "Oxytocin IV / IM", group: "Medicines", minutes: 2, kind: "med" },
      { id: "misoprostol", label: "Misoprostol per protocol", group: "Medicines", minutes: 2, kind: "med" },
      { id: "fluid_bolus", label: "Crystalloid bolus", group: "Medicines", minutes: 2, kind: "med" },
      { id: "consent", label: "Explain to couple", group: "Disposition", minutes: 2, kind: "disposition" },
      { id: "referral_higher", label: "Escalate to CHC / blood bank", group: "Disposition", minutes: 5, kind: "disposition" },
      { id: "discharge_home", label: "Reassure & send home", group: "Disposition", minutes: 2, kind: "disposition" },
    ],
    rubric: [
      { id: "pph.shock_recognition", label: "Shock recognized (HR/BP/clots cluster)", axis: "diagnosis", points: 14, orderId: "vitals", required: true, failCaseOnMiss: true, windowMin: [0, 8] },
      { id: "pph.uterotonic", label: "Uterotonic within window", axis: "procedure", points: 16, orderId: "oxytocin", required: true, failCaseOnMiss: true, windowMin: [0, 15] },
      { id: "pph.escalation", label: "Escalate for blood / surgery capability", axis: "timing", points: 12, orderId: "referral_higher", required: true, failCaseOnMiss: true },
      { id: "pph.massage", label: "Uterine massage / bimanual compression", axis: "procedure", points: 10, orderId: "uterine_massage", required: false },
      { id: "pph.iv", label: "IV access for resuscitation", axis: "procedure", points: 8, orderId: "iv_access", required: false },
      { id: "pph.communication", label: "Family communication in vernacular", axis: "communication", points: 6, orderId: "consent", required: false },
      { id: "pph.home", label: "Sent home while bleeding", axis: "safety", points: 0, orderId: "discharge_home", required: false, failCaseOnHit: true },
    ],
    competencies: [
      "pph.recognition",
      "uterotonic.protocol",
      "shock.resuscitation",
      "referral-constraint",
      "respectful-maternity",
    ],
    findings: {
      vitals: "HR 128, BP 82/54, pale, ongoing clots. Young patient — shock can be missed.",
      uterine_massage: "Uterus boggy. Massage produces clot expulsion; bleeding slows modestly.",
      examine_placenta: "Placental fragment suspected in passed tissue — incomplete third stage likely.",
      oxytocin: "Uterotonic given. Tone improves; bleeding decreases but not resolved.",
      hemoglobin: "Hb 6.8 g/dL. Cross-match requested — O-negative rarely stocked at PHC.",
    },
  },
  {
    id: "arjun-dengue",
    version: "arjun_reddy.dengue.warning_signs.v1",
    title: "Paediatric dengue — critical phase",
    specialty: "Paediatrics / Infectious disease",
    durationMin: 30,
    persona: {
      name: "Arjun Reddy",
      age: 8,
      sex: "M",
      city: "Hyderabad",
      language: "te / en",
      register: "Mother is software engineer; anxious, has Googled dengue",
      literacy: "Child; mother is historian",
      occupation: "Class 3 student",
      summary: "Day 4 of fever — now afebrile but lethargic, abdominal pain, one vomit.",
      openingLine: "Amma: Doctor, fever went down but he is very dull today. Tummy pain since morning.",
      voice: "Mother fast Telugu-English. Child lethargic, answers in monosyllables.",
      informant: { name: "Mrs. Reddy", relation: "mother", age: 34 },
    },
    briefing:
      "8-year-old at corporate hospital ER Hyderabad, monsoon season. Day 4 illness — fever broke overnight but child is worse. Platelets 62k (was 140k), hematocrit rising. Mother is educated and anxious. Critical-phase recognition is the pedagogical spine.",
    hidden:
      "Dengue critical phase (defervescence). Required: recognize critical transition, weight-based fluid (ml/kg), admit vs observe decision, warning-sign counseling. Forbidden: treat 'fever down' as improvement, adult fluid volumes, dismiss parental concern.",
    initialVitals: { hr: 118, sbp: 98, dbp: 62, spo2: 97, rr: 26, pain: 5, tempC: 37.2 },
    orders: [
      { id: "greet_native", label: "Greet mother, acknowledge concern", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "caregiver_history", label: "Fever curve & intake history", group: "Bedside", minutes: 3, kind: "bedside" },
      { id: "vitals", label: "Full vitals + perfusion", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "weight", label: "Weight for ml/kg fluids", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "labs", label: "Repeat CBC / hematocrit", group: "Diagnostics", minutes: 4, kind: "diagnostic" },
      { id: "ns1", label: "NS1 / dengue serology", group: "Diagnostics", minutes: 3, kind: "diagnostic" },
      { id: "iv_fluids", label: "Isotonic fluids ml/kg (protocol)", group: "Medicines", minutes: 4, kind: "med" },
      { id: "adult_bolus", label: "20 ml/kg bolus (PALS adult reflex)", group: "Medicines", minutes: 2, kind: "med" },
      { id: "discharge", label: "Discharge — fever is down", group: "Disposition", minutes: 2, kind: "disposition" },
      { id: "admit", label: "Admit for critical phase", group: "Disposition", minutes: 3, kind: "disposition" },
      { id: "counsel", label: "Warning signs counseling", group: "Disposition", minutes: 4, kind: "disposition" },
    ],
    rubric: [
      { id: "dengue.critical_phase", label: "Critical phase recognized despite afebrile", axis: "diagnosis", points: 16, orderId: "vitals", required: true, failCaseOnMiss: true },
      { id: "dengue.fluid_ml_kg", label: "Weight-based fluid protocol", axis: "procedure", points: 14, orderId: "iv_fluids", required: true, failCaseOnMiss: true },
      { id: "dengue.admit", label: "Admit / observe appropriately", axis: "timing", points: 12, orderId: "admit", required: true, failCaseOnMiss: true },
      { id: "dengue.counsel", label: "Warning sign counseling to mother", axis: "communication", points: 8, orderId: "counsel", required: false },
      { id: "dengue.labs", label: "Repeat labs / hematocrit trend", axis: "diagnosis", points: 6, orderId: "labs", required: false },
      { id: "dengue.discharge_trap", label: "Discharged during critical phase", axis: "safety", points: 0, orderId: "discharge", required: false, failCaseOnHit: true },
    ],
    competencies: ["paeds.dengue", "critical-phase.recognition", "fluid.ml_kg", "caregiver-history"],
    findings: {
      vitals: "Afebrile but lethargic, mild tachycardia, cap refill 3s, BP low-normal for age.",
      labs: "Platelets 62,000 (down from 140k). Hematocrit up 8% — plasma leak phase.",
      iv_fluids: "Maintenance + deficit calculated at 22 ml/kg — pediatric dengue protocol.",
      counsel: "Mother verbalizes warning signs: bleeding, severe pain, cold extremities, reduced urine.",
    },
  },
  {
    id: "priya-snakebite",
    version: "priya_nair.snakebite.russells_viper.v1",
    title: "Russell's viper envenomation — paddy field",
    specialty: "Emergency / Toxicology",
    durationMin: 25,
    persona: {
      name: "Priya Nair",
      age: 28,
      sex: "F",
      city: "Kochi outskirts",
      language: "ml / en",
      register: "Rice paddy worker; delayed after traditional healer visit",
      literacy: "Primary school",
      occupation: "Agricultural worker",
      summary: "Bitten 2h ago on right ankle. Swelling, gum bleeding, cola-colored urine.",
      openingLine: "Doctor, pambu kachichu — ozhichilil poyi. Ippo blood mutathilum urineyilum.",
      voice: "Malayalam-primary, frightened, minimizes healer detour unless asked.",
    },
    briefing:
      "28-year-old rice paddy worker, Russell's viper bite 2 hours ago (healer detour cost 90 minutes). Gum bleeding, hematuria, WBCT20 no clot at 20 min. BP 96/60. ASV dosing in India: 10 vials initial, not weight-based.",
    hidden:
      "Hemotoxic + nephrotoxic envenomation. Required: WBCT20 interpretation, 10 vial ASV start, AKI monitoring, NO fasciotomy. Hidden timeline: traditional healer first. Forbidden: weight-based ASV calc, fasciotomy for swelling.",
    initialVitals: { hr: 110, sbp: 96, dbp: 58, spo2: 96, rr: 22, pain: 6, tempC: 36.9 },
    orders: [
      { id: "greet_native", label: "Greet in Malayalam", group: "Bedside", minutes: 1, kind: "bedside" },
      { id: "history", label: "Bite timeline + healer detour", group: "Bedside", minutes: 3, kind: "bedside" },
      { id: "vitals", label: "Vitals + bite site", group: "Bedside", minutes: 2, kind: "bedside" },
      { id: "wbct20", label: "WBCT20 (whole blood clotting)", group: "Diagnostics", minutes: 3, kind: "diagnostic" },
      { id: "asv_10", label: "ASV 10 vials IV (standard initial)", group: "Medicines", minutes: 5, kind: "med" },
      { id: "asv_weight", label: "ASV dose by body weight", group: "Medicines", minutes: 2, kind: "med" },
      { id: "fasciotomy", label: "Fasciotomy for swelling", group: "Medicines", minutes: 4, kind: "med" },
      { id: "creatinine", label: "Creatinine / urine output", group: "Diagnostics", minutes: 3, kind: "diagnostic" },
      { id: "referral_higher", label: "Refer to tertiary / ICU", group: "Disposition", minutes: 4, kind: "disposition" },
    ],
    rubric: [
      { id: "snake.wbct20", label: "WBCT20 interpreted correctly", axis: "diagnosis", points: 14, orderId: "wbct20", required: true, failCaseOnMiss: true },
      { id: "snake.asv_10", label: "ASV 10 vials initial dose", axis: "procedure", points: 16, orderId: "asv_10", required: true, failCaseOnMiss: true },
      { id: "snake.aki_monitor", label: "AKI monitoring (creatinine/UO)", axis: "diagnosis", points: 10, orderId: "creatinine", required: false },
      { id: "snake.timeline", label: "Healer detour elicited without judgment", axis: "communication", points: 8, orderId: "history", required: false },
      { id: "snake.fasciotomy_trap", label: "Fasciotomy for viper swelling", axis: "safety", points: 0, orderId: "fasciotomy", required: false, failCaseOnHit: true },
      { id: "snake.asv_weight_trap", label: "Weight-based ASV dosing", axis: "safety", points: 0, orderId: "asv_weight", required: false, failCaseOnHit: true },
    ],
    competencies: ["snakebite.envenomation", "asv.protocol", "wbct20", "aki.monitoring"],
    findings: {
      wbct20: "WBCT20 at 20 min: blood has NOT clotted — coagulopathy confirmed.",
      asv_10: "10 vials polyvalent ASV started. Repeat WBCT at 6 hours planned.",
      creatinine: "Creatinine rising. Urine output falling — AKI watch.",
      history: "Patient admits ozhichil practitioner first — 90 min delay to hospital.",
    },
  },
];

export function getCase(id: string | undefined, extra: CaseBlueprint[] = []): CaseBlueprint | undefined {
  if (!id) return undefined;
  return CASES.find((c) => c.id === id) ?? extra.find((c) => c.id === id);
}

/** Who speaks in the chat panel — informant for proxy cases. */
export function dialogueSpeaker(bp: CaseBlueprint): string {
  if (bp.persona.informant) {
    return `${bp.persona.informant.name} (${bp.persona.informant.relation})`;
  }
  return bp.persona.name;
}

export function isCaseId(id: string, extra: CaseBlueprint[] = []): boolean {
  return Boolean(getCase(id, extra));
}

export { caseSupportsBackend } from "./action-map";
