export const MODULES = [
  {
    id: "pratibimb" as const,
    to: "/cases" as const,
    name: "Pratibimb",
    sanskrit: "reflection",
    job: "Clinical twin. Vernacular patient, deterministic physiology.",
    standalone: "A college can run one case with no other modules.",
  },
  {
    id: "nirikshak" as const,
    to: "/ledger" as const,
    name: "Nirikshak",
    sanskrit: "examiner",
    job: "Fail-closed grader. Replayable evidence, never an opaque LLM score.",
    standalone: "Needs a frozen session from Pratibimb or Drishti.",
  },
  {
    id: "dhaara" as const,
    to: "/dhaara" as const,
    name: "Dhaara",
    sanskrit: "flow",
    job: "Live competency graph with decay. CRS is a vector, not a badge.",
    standalone: "Reads the ledger. Empty until evidence exists.",
  },
  {
    id: "guru" as const,
    to: "/guru" as const,
    name: "Guru",
    sanskrit: "teacher",
    job: "Tutor aimed at Dhaara gaps. Does not invent doses without a cite.",
    standalone: "Works as a coach; mastery still comes from the ledger.",
  },
  {
    id: "drishti" as const,
    to: "/drishti" as const,
    name: "Drishti",
    sanskrit: "sight",
    job: "Floor observation. Preceptor-scored steps, not a fake badge-cam.",
    standalone: "A hospital preceptor can log one procedure today.",
  },
  {
    id: "niyukti" as const,
    to: "/niyukti" as const,
    name: "Niyukti",
    sanskrit: "appointment",
    job: "Match CRS vectors to hospital demand. No hiring decision.",
    standalone: "Needs a CRS. Does not write into the ledger.",
  },
  {
    id: "sankalp" as const,
    to: "/sankalp" as const,
    name: "Sankalp",
    sanskrit: "resolution",
    job: "Next action from the weakest competencies.",
    standalone: "A plan. Execution is Pratibimb or Drishti.",
  },
  {
    id: "aayam" as const,
    to: "/aayam" as const,
    name: "Aayam",
    sanskrit: "dimension",
    job: "Audit pack. Evidence-anchored credential, not a blockchain stunt.",
    standalone: "Needs a graded session. Regulator paper is the display, not a filing.",
  },
  {
    id: "beema" as const,
    to: "/beema" as const,
    name: "BEEMA",
    sanskrit: "protection",
    job: "Safety intelligence. Reads the ledger. Never prices a person.",
    standalone: "v0.1 signals only. No employment, no underwriting.",
  },
  {
    id: "author" as const,
    to: "/author" as const,
    name: "Authoring",
    sanskrit: "harness",
    job: "Faculty writes a case. Dry-run against the engine. Draft-tier.",
    standalone: "Produces a blueprint. Production still needs a clinician countersign.",
  },
];

export type ModuleId = (typeof MODULES)[number]["id"];

export const COMPETENCIES = [
  { id: "cardiac.stemi", label: "cardiac.stemi", domain: "cardiac" },
  { id: "ecg.inferior", label: "ecg.inferior", domain: "cardiac" },
  { id: "communication.marathi", label: "communication.marathi", domain: "communication" },
  { id: "emergency.triage", label: "emergency.triage", domain: "cardiac" },
  { id: "stemi-recognition", label: "STEMI recognition", domain: "cardiac" },
  { id: "ecg-acquisition", label: "ECG acquisition", domain: "cardiac" },
  { id: "acs-antiplatelet", label: "Antiplatelet in ACS", domain: "cardiac" },
  { id: "rv-infarct", label: "RV-infarct caution", domain: "cardiac" },
  { id: "pci-pathway", label: "PCI pathway", domain: "cardiac" },
  { id: "vernacular-consent", label: "Vernacular consent", domain: "communication" },
  { id: "pet-recognition", label: "Severe PET recognition", domain: "obstetric" },
  { id: "proteinuria", label: "Proteinuria testing", domain: "obstetric" },
  { id: "mgso4", label: "MgSO4 protocol", domain: "obstetric" },
  { id: "htn-pregnancy", label: "Hypertension in pregnancy", domain: "obstetric" },
  { id: "referral-constraint", label: "Referral under constraint", domain: "obstetric" },
  { id: "respectful-maternity", label: "Respectful maternity care", domain: "communication" },
  { id: "paeds-resp", label: "Paediatric respiratory assessment", domain: "paeds" },
  { id: "asthma-exacerbation", label: "Asthma exacerbation", domain: "paeds" },
  { id: "caregiver-history", label: "Caregiver history", domain: "communication" },
  { id: "bronchodilator-steroid", label: "Bronchodilator + steroid", domain: "paeds" },
  { id: "avoid-harm", label: "Avoid harmful meds", domain: "safety" },
  { id: "device-teaching", label: "Device teaching", domain: "paeds" },
  { id: "iv-cannula", label: "IV cannulation", domain: "procedure" },
  { id: "ecg-leads", label: "ECG lead placement", domain: "procedure" },
  { id: "bmw", label: "Biomedical waste segregation", domain: "procedure" },
  { id: "sbar", label: "SBAR handoff", domain: "communication" },
  { id: "dx.allergic_emergency", label: "dx.allergic_emergency", domain: "safety" },
  { id: "rx.anaphylaxis_first_line", label: "rx.anaphylaxis_first_line", domain: "safety" },
  { id: "safety.route_selection", label: "safety.route_selection", domain: "safety" },
  { id: "safety.allergen_avoidance", label: "safety.allergen_avoidance", domain: "safety" },
  { id: "neonatal.sepsis", label: "neonatal.sepsis", domain: "neonatal" },
  { id: "nursing.assessment", label: "nursing.assessment", domain: "neonatal" },
  { id: "communication.tamil", label: "communication.tamil", domain: "communication" },
  { id: "pph.recognition", label: "PPH recognition", domain: "obstetric" },
  { id: "uterotonic.protocol", label: "Uterotonic protocol", domain: "obstetric" },
  { id: "shock.resuscitation", label: "Shock resuscitation", domain: "obstetric" },
  { id: "oxygen-titration", label: "Oxygen titration", domain: "procedure" },
  { id: "paeds.dengue", label: "Paediatric dengue", domain: "paeds" },
  { id: "critical-phase.recognition", label: "Dengue critical phase", domain: "paeds" },
  { id: "fluid.ml_kg", label: "Weight-based fluids ml/kg", domain: "paeds" },
  { id: "snakebite.envenomation", label: "Snakebite envenomation", domain: "toxicology" },
  { id: "asv.protocol", label: "ASV protocol (10 vial rule)", domain: "toxicology" },
  { id: "wbct20", label: "WBCT20 interpretation", domain: "toxicology" },
  { id: "aki.monitoring", label: "AKI monitoring", domain: "toxicology" },
] as const;

export type CompetencyId = (typeof COMPETENCIES)[number]["id"];

export const CASE_COMP_MAP: Record<string, CompetencyId[]> = {
  "ramesh-stemi": [
    "cardiac.stemi",
    "ecg.inferior",
    "communication.marathi",
    "emergency.triage",
  ],
  "sunita-preeclampsia": [
    "pet-recognition",
    "proteinuria",
    "mgso4",
    "htn-pregnancy",
    "referral-constraint",
    "respectful-maternity",
  ],
  "arjun-asthma": [
    "paeds-resp",
    "asthma-exacerbation",
    "caregiver-history",
    "bronchodilator-steroid",
    "avoid-harm",
    "device-teaching",
  ],
  "opd-anaphylaxis": [
    "dx.allergic_emergency",
    "rx.anaphylaxis_first_line",
    "safety.route_selection",
    "safety.allergen_avoidance",
  ],
  "aarav-sepsis": [
    "neonatal.sepsis",
    "nursing.assessment",
    "communication.tamil",
    "emergency.triage",
  ],
  "sunita-pph": [
    "pph.recognition",
    "uterotonic.protocol",
    "shock.resuscitation",
    "referral-constraint",
    "respectful-maternity",
  ],
  "arjun-dengue": [
    "paeds.dengue",
    "critical-phase.recognition",
    "fluid.ml_kg",
    "caregiver-history",
  ],
  "priya-snakebite": [
    "snakebite.envenomation",
    "asv.protocol",
    "wbct20",
    "aki.monitoring",
  ],
};

export const HOSPITALS = [
  {
    id: "gmc-nagpur",
    name: "GMC Nagpur — casualty",
    city: "Nagpur",
    role: "Emergency technician / intern",
    minCrs: 72,
    need: ["cardiac.stemi", "ecg.inferior", "emergency.triage", "sbar"] as CompetencyId[],
    language: "mr / hi",
    nights: true,
  },
  {
    id: "fru-araria",
    name: "FRU Araria",
    city: "Araria",
    role: "ANM / obstetric MO support",
    minCrs: 68,
    need: ["pet-recognition", "mgso4", "referral-constraint", "respectful-maternity"] as CompetencyId[],
    language: "hi / bho",
    nights: true,
  },
  {
    id: "niloufer-hyd",
    name: "Niloufer paediatric casualty",
    city: "Hyderabad",
    role: "Paediatric ward technician",
    minCrs: 70,
    need: ["paeds-resp", "asthma-exacerbation", "caregiver-history", "oxygen-titration"] as CompetencyId[],
    language: "te / en",
    nights: true,
  },
  {
    id: "state-mission",
    name: "State health mission — allied pool",
    city: "Multiple",
    role: "Deployable allied-health",
    minCrs: 60,
    need: ["iv-cannula", "bmw", "sbar", "oxygen-titration"] as CompetencyId[],
    language: "hi / en",
    nights: false,
  },
];

export const PROCEDURES = [
  {
    id: "iv-cannula",
    label: "Peripheral IV cannula",
    competencies: ["iv-cannula"] as CompetencyId[],
    steps: [
      { id: "consent", label: "Explain in the patient’s language" },
      { id: "hand", label: "Hand hygiene + gloves" },
      { id: "tourniquet", label: "Tourniquet and vein choice" },
      { id: "asepsis", label: "Skin asepsis, dry time" },
      { id: "flashback", label: "Flashback, advance, secure" },
      { id: "sharps", label: "Sharps disposal + BMW" },
    ],
  },
  {
    id: "ecg-leads",
    label: "12-lead ECG placement",
    competencies: ["ecg-leads", "ecg-acquisition"] as CompetencyId[],
    steps: [
      { id: "prepare", label: "Skin prep, privacy" },
      { id: "limb", label: "Limb leads correct" },
      { id: "v1v2", label: "V1–V2 sternal border" },
      { id: "v4", label: "V4 midclavicular 5th ICS" },
      { id: "v5v6", label: "V5–V6 axillary line" },
      { id: "label", label: "Label, time, handoff" },
    ],
  },
  {
    id: "bmw",
    label: "Biomedical waste segregation",
    competencies: ["bmw"] as CompetencyId[],
    steps: [
      { id: "yellow", label: "Yellow — anatomical / soiled" },
      { id: "red", label: "Red — recyclable contaminated" },
      { id: "white", label: "White — sharps" },
      { id: "blue", label: "Blue — glass" },
      { id: "liners", label: "Liners 3/4, tied, labelled" },
    ],
  },
  {
    id: "sbar",
    label: "SBAR handoff",
    competencies: ["sbar"] as CompetencyId[],
    steps: [
      { id: "s", label: "Situation — who, where, why now" },
      { id: "b", label: "Background — relevant history" },
      { id: "a", label: "Assessment — vitals + working diagnosis" },
      { id: "r", label: "Recommendation — ask, not dump" },
    ],
  },
];
