"""
Grading blueprint for anaphylaxis — OPD, post-injection ceftriaxone.

Every hit states a behaviour worth credit. The safety axis is phrased as
demonstrated safe practice ("IV adrenaline bolus withheld") rather than as a
penalty, so a miss scores zero and criticality is carried by
`required` + `fail_case_on_violation`.
"""
from __future__ import annotations

from services.pratibimb.app.eval.rubric import (
    Axis,
    GradingBlueprint,
    RubricHit,
    Severity,
)

ANAPHYLAXIS_BLUEPRINT = GradingBlueprint(
    case_id="ANAPHYLAXIS_OPD_001",
    case_version="1.0.0",
    rubric_version="0.3.0",
    display_name="Anaphylaxis — OPD, post-injection ceftriaxone",
    hits=(
        # ── Diagnostic ───────────────────────────────────────────────────
        RubricHit(
            id="dx.anaphylaxis",
            axis=Axis.DIAGNOSTIC,
            matcher="diagnosis_stated",
            params={
                "dx": "anaphylaxis",
                "aliases": ("anaphylactic shock", "severe allergic reaction"),
                "within_s": 180,
                "min_confidence": 0.5,
            },
            points=10,
            severity=Severity.MAJOR,
            required=True,
            fail_case_on_violation=True,
            description="Anaphylaxis identified within 3 min",
            competencies=("dx.allergic_emergency",),
        ),
        RubricHit(
            id="dx.hypotension",
            axis=Axis.DIAGNOSTIC,
            matcher="vital_recognized",
            params={"token": "sbp_low", "within_s": 120},
            points=4,
            description="Hypotension recognised within 2 min",
            competencies=("dx.shock_recognition",),
        ),
        RubricHit(
            id="dx.desaturation",
            axis=Axis.DIAGNOSTIC,
            matcher="vital_recognized",
            params={"token": "spo2_low", "within_s": 120},
            points=3,
            description="Falling SpO2 recognised within 2 min",
            competencies=("dx.respiratory_assessment",),
        ),
        RubricHit(
            id="dx.stridor",
            axis=Axis.DIAGNOSTIC,
            matcher="physical_sign_identified",
            params={"token": "stridor"},
            points=3,
            description="Upper airway compromise identified",
            competencies=("dx.airway_assessment",),
        ),
        RubricHit(
            id="dx.urticaria",
            axis=Axis.DIAGNOSTIC,
            matcher="finding_recognized",
            params={"token": "urticaria"},
            points=2,
            description="Cutaneous involvement noted",
            competencies=("dx.allergic_emergency",),
        ),
        RubricHit(
            id="hx.allergy_asked",
            axis=Axis.DIAGNOSTIC,
            matcher="symptom_elicited",
            params={"token": "allergy_history"},
            points=4,
            description="Allergy history elicited",
            competencies=("hx.focused_history",),
        ),

        # ── Action ───────────────────────────────────────────────────────
        RubricHit(
            id="act.adrenaline_im",
            axis=Axis.ACTION,
            matcher="drug_given",
            params={
                "drug_id": "adrenaline",
                "route": "IM",
                "min_dose": 0.3,
                "max_dose": 0.5,
                "within_s": 300,
            },
            points=15,
            severity=Severity.CRITICAL,
            required=True,
            fail_case_on_violation=True,
            description="IM adrenaline 0.3-0.5 mg within 5 min",
            competencies=("rx.anaphylaxis_first_line",),
        ),
        RubricHit(
            id="act.oxygen",
            axis=Axis.ACTION,
            matcher="order_placed",
            params={"order_id": "oxygen", "params": {"lpm_min": 6}, "within_s": 240},
            points=6,
            description="High-flow oxygen at 6 L/min or more",
            competencies=("rx.oxygen_therapy",),
        ),
        RubricHit(
            id="act.iv_fluids",
            axis=Axis.ACTION,
            matcher="order_placed",
            params={
                "order_id": "iv_fluids",
                "params": {"fluid": "NS", "bolus_ml_min": 500},
                "within_s": 600,
            },
            points=8,
            description="Normal saline bolus of 500 mL or more",
            competencies=("rx.fluid_resuscitation",),
        ),
        RubricHit(
            id="act.position",
            axis=Axis.ACTION,
            matcher="order_placed",
            params={"order_id": "position_supine_legs_raised"},
            points=4,
            description="Supine with legs raised",
            competencies=("rx.positioning",),
        ),
        RubricHit(
            id="act.hydrocortisone",
            axis=Axis.ACTION,
            matcher="drug_given",
            params={"drug_id": "hydrocortisone", "route": "IV", "min_dose": 100},
            points=6,
            description="IV hydrocortisone 100 mg or more",
            competencies=("rx.corticosteroid",),
        ),
        RubricHit(
            id="act.antihistamine",
            axis=Axis.ACTION,
            matcher="drug_given",
            params={"drug_id": "pheniramine", "route": "IV"},
            points=5,
            description="IV H1 antihistamine",
            competencies=("rx.antihistamine",),
        ),
        RubricHit(
            id="act.airway_ready",
            axis=Axis.ACTION,
            matcher="order_placed",
            params={"order_id": "prepare_intubation", "within_s": 600},
            points=5,
            description="Airway equipment prepared",
            competencies=("rx.airway_management",),
        ),

        # ── Timing ───────────────────────────────────────────────────────
        RubricHit(
            id="time.adrenaline_fast",
            axis=Axis.TIMING,
            matcher="action_within",
            params={"inner_hit": "act.adrenaline_im", "within_s": 180},
            points=8,
            severity=Severity.MAJOR,
            description="IM adrenaline within 3 min",
            competencies=("rx.anaphylaxis_first_line",),
        ),
        RubricHit(
            id="time.oxygen_fast",
            axis=Axis.TIMING,
            matcher="action_within",
            params={"inner_hit": "act.oxygen", "within_s": 240},
            points=4,
            description="Oxygen within 4 min",
            competencies=("rx.oxygen_therapy",),
        ),
        RubricHit(
            id="time.resus_order",
            axis=Axis.TIMING,
            matcher="sequence",
            params={
                "steps": ["dx.anaphylaxis", "act.adrenaline_im", "act.iv_fluids"],
                "max_gap_s": 300,
            },
            points=6,
            description="Diagnosis, then IM adrenaline, then fluids",
            competencies=("rx.resuscitation_sequencing",),
        ),
        RubricHit(
            id="time.repeat_adrenaline",
            axis=Axis.TIMING,
            matcher="flag_present",
            params={"flag": "adrenaline_repeat_considered", "within_s": 900},
            points=4,
            description="Repeat adrenaline considered when response inadequate",
            competencies=("rx.reassessment",),
        ),

        # ── Safety (all phrased as safe practice demonstrated) ───────────
        RubricHit(
            id="safe.iv_adrenaline_withheld",
            axis=Axis.SAFETY,
            matcher="drug_not_given",
            params={"drug_id": "adrenaline", "route": "IV"},
            points=10,
            severity=Severity.CRITICAL,
            required=True,
            fail_case_on_violation=True,
            description="IV adrenaline bolus correctly withheld in a conscious patient",
            competencies=("safety.route_selection",),
        ),
        RubricHit(
            id="safe.allergen_not_repeated",
            axis=Axis.SAFETY,
            matcher="drug_not_given",
            params={"drug_id": "ceftriaxone"},
            points=6,
            severity=Severity.MAJOR,
            required=True,
            fail_case_on_violation=True,
            description="Suspected allergen not re-administered",
            competencies=("safety.allergen_avoidance",),
        ),
        RubricHit(
            id="safe.beta_blocker_withheld",
            axis=Axis.SAFETY,
            matcher="drug_not_given",
            params={"drug_id": "metoprolol"},
            points=6,
            severity=Severity.MAJOR,
            description="Beta-blocker withheld during anaphylaxis",
            competencies=("safety.contraindication_awareness",),
        ),
        RubricHit(
            id="safe.allergy_documented",
            axis=Axis.SAFETY,
            matcher="flag_present",
            params={"flag": "allergy_documented"},
            points=4,
            description="Allergy documented in the record",
            competencies=("safety.documentation",),
        ),
        RubricHit(
            id="safe.observation_period",
            axis=Axis.SAFETY,
            matcher="order_placed",
            params={"order_id": "observe_biphasic"},
            points=4,
            description="Observation ordered for biphasic reaction",
            competencies=("safety.disposition",),
        ),

        # ── Communication ────────────────────────────────────────────────
        RubricHit(
            id="comm.sbar_handoff",
            axis=Axis.COMMUNICATION,
            matcher="handoff_given",
            params={
                "required_fields": ("situation", "background", "assessment", "recommendation"),
            },
            points=5,
            description="Structured SBAR handoff",
            competencies=("comm.handoff",),
        ),
        RubricHit(
            id="comm.escalation",
            axis=Axis.COMMUNICATION,
            matcher="escalation",
            params={"target": "physician_on_call", "within_s": 300},
            points=4,
            description="Escalated to the on-call physician within 5 min",
            competencies=("comm.escalation",),
        ),
        RubricHit(
            id="comm.family_consent",
            axis=Axis.COMMUNICATION,
            matcher="flag_present",
            params={"flag": "consent_explained_family"},
            points=3,
            description="Situation explained to family",
            competencies=("comm.family_communication",),
        ),
    ),
    weights={
        Axis.DIAGNOSTIC: 0.20,
        Axis.ACTION: 0.30,
        Axis.TIMING: 0.15,
        Axis.SAFETY: 0.25,
        Axis.COMMUNICATION: 0.10,
    },
    pass_threshold=0.65,
)
