/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AayamRouteImport } from './routes/aayam'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as BeemaRouteImport } from './routes/beema'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CrsRouteImport } from './routes/crs'
import { Route as DhaaraRouteImport } from './routes/dhaara'
import { Route as DrishtiRouteImport } from './routes/drishti'
import { Route as GuruRouteImport } from './routes/guru'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as NiyuktiRouteImport } from './routes/niyukti'
import { Route as OsRouteImport } from './routes/os'
import { Route as SankalpRouteImport } from './routes/sankalp'
import { Route as DebriefSessionIdRouteImport } from './routes/debrief.$sessionId'
import { Route as SimCaseIdRouteImport } from './routes/sim.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AayamRoute = AayamRouteImport.update({
  id: '/aayam',
  path: '/aayam',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const BeemaRoute = BeemaRouteImport.update({
  id: '/beema',
  path: '/beema',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CrsRoute = CrsRouteImport.update({
  id: '/crs',
  path: '/crs',
  getParentRoute: () => rootRouteImport,
} as any)
const DhaaraRoute = DhaaraRouteImport.update({
  id: '/dhaara',
  path: '/dhaara',
  getParentRoute: () => rootRouteImport,
} as any)
const DrishtiRoute = DrishtiRouteImport.update({
  id: '/drishti',
  path: '/drishti',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruRoute = GuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const NiyuktiRoute = NiyuktiRouteImport.update({
  id: '/niyukti',
  path: '/niyukti',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const SankalpRoute = SankalpRouteImport.update({
  id: '/sankalp',
  path: '/sankalp',
  getParentRoute: () => rootRouteImport,
} as any)
const DebriefSessionIdRoute = DebriefSessionIdRouteImport.update({
  id: '/debrief/$sessionId',
  path: '/debrief/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimCaseIdRoute = SimCaseIdRouteImport.update({
  id: '/sim/$caseId',
  path: '/sim/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aayam': typeof AayamRoute
  '/author': typeof AuthorRoute
  '/beema': typeof BeemaRoute
  '/cases': typeof CasesRoute
  '/crs': typeof CrsRoute
  '/dhaara': typeof DhaaraRoute
  '/drishti': typeof DrishtiRoute
  '/guru': typeof GuruRoute
  '/ledger': typeof LedgerRoute
  '/niyukti': typeof NiyuktiRoute
  '/os': typeof OsRoute
  '/sankalp': typeof SankalpRoute
  '/debrief/$sessionId': typeof DebriefSessionIdRoute
  '/sim/$caseId': typeof SimCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aayam': typeof AayamRoute
  '/author': typeof AuthorRoute
  '/beema': typeof BeemaRoute
  '/cases': typeof CasesRoute
  '/crs': typeof CrsRoute
  '/dhaara': typeof DhaaraRoute
  '/drishti': typeof DrishtiRoute
  '/guru': typeof GuruRoute
  '/ledger': typeof LedgerRoute
  '/niyukti': typeof NiyuktiRoute
  '/os': typeof OsRoute
  '/sankalp': typeof SankalpRoute
  '/debrief/$sessionId': typeof DebriefSessionIdRoute
  '/sim/$caseId': typeof SimCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aayam': typeof AayamRoute
  '/author': typeof AuthorRoute
  '/beema': typeof BeemaRoute
  '/cases': typeof CasesRoute
  '/crs': typeof CrsRoute
  '/dhaara': typeof DhaaraRoute
  '/drishti': typeof DrishtiRoute
  '/guru': typeof GuruRoute
  '/ledger': typeof LedgerRoute
  '/niyukti': typeof NiyuktiRoute
  '/os': typeof OsRoute
  '/sankalp': typeof SankalpRoute
  '/debrief/$sessionId': typeof DebriefSessionIdRoute
  '/sim/$caseId': typeof SimCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aayam'
    | '/author'
    | '/beema'
    | '/cases'
    | '/crs'
    | '/dhaara'
    | '/drishti'
    | '/guru'
    | '/ledger'
    | '/niyukti'
    | '/os'
    | '/sankalp'
    | '/debrief/$sessionId'
    | '/sim/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aayam'
    | '/author'
    | '/beema'
    | '/cases'
    | '/crs'
    | '/dhaara'
    | '/drishti'
    | '/guru'
    | '/ledger'
    | '/niyukti'
    | '/os'
    | '/sankalp'
    | '/debrief/$sessionId'
    | '/sim/$caseId'
  id:
    | '__root__'
    | '/'
    | '/aayam'
    | '/author'
    | '/beema'
    | '/cases'
    | '/crs'
    | '/dhaara'
    | '/drishti'
    | '/guru'
    | '/ledger'
    | '/niyukti'
    | '/os'
    | '/sankalp'
    | '/debrief/$sessionId'
    | '/sim/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AayamRoute: typeof AayamRoute
  AuthorRoute: typeof AuthorRoute
  BeemaRoute: typeof BeemaRoute
  CasesRoute: typeof CasesRoute
  CrsRoute: typeof CrsRoute
  DhaaraRoute: typeof DhaaraRoute
  DrishtiRoute: typeof DrishtiRoute
  GuruRoute: typeof GuruRoute
  LedgerRoute: typeof LedgerRoute
  NiyuktiRoute: typeof NiyuktiRoute
  OsRoute: typeof OsRoute
  SankalpRoute: typeof SankalpRoute
  DebriefSessionIdRoute: typeof DebriefSessionIdRoute
  SimCaseIdRoute: typeof SimCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aayam': {
      id: '/aayam'
      path: '/aayam'
      fullPath: '/aayam'
      preLoaderRoute: typeof AayamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beema': {
      id: '/beema'
      path: '/beema'
      fullPath: '/beema'
      preLoaderRoute: typeof BeemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crs': {
      id: '/crs'
      path: '/crs'
      fullPath: '/crs'
      preLoaderRoute: typeof CrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhaara': {
      id: '/dhaara'
      path: '/dhaara'
      fullPath: '/dhaara'
      preLoaderRoute: typeof DhaaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drishti': {
      id: '/drishti'
      path: '/drishti'
      fullPath: '/drishti'
      preLoaderRoute: typeof DrishtiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niyukti': {
      id: '/niyukti'
      path: '/niyukti'
      fullPath: '/niyukti'
      preLoaderRoute: typeof NiyuktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sankalp': {
      id: '/sankalp'
      path: '/sankalp'
      fullPath: '/sankalp'
      preLoaderRoute: typeof SankalpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debrief/$sessionId': {
      id: '/debrief/$sessionId'
      path: '/debrief/$sessionId'
      fullPath: '/debrief/$sessionId'
      preLoaderRoute: typeof DebriefSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim/$caseId': {
      id: '/sim/$caseId'
      path: '/sim/$caseId'
      fullPath: '/sim/$caseId'
      preLoaderRoute: typeof SimCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AayamRoute: AayamRoute,
  AuthorRoute: AuthorRoute,
  BeemaRoute: BeemaRoute,
  CasesRoute: CasesRoute,
  CrsRoute: CrsRoute,
  DhaaraRoute: DhaaraRoute,
  DrishtiRoute: DrishtiRoute,
  GuruRoute: GuruRoute,
  LedgerRoute: LedgerRoute,
  NiyuktiRoute: NiyuktiRoute,
  OsRoute: OsRoute,
  SankalpRoute: SankalpRoute,
  DebriefSessionIdRoute: DebriefSessionIdRoute,
  SimCaseIdRoute: SimCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
